#!/usr/bin/gawk -E

# Autor: Ulpiano Tur de Vargas <ulpiano.tur.devargas@gmail.com>
#
# Este programa es software libre; puedes distribuirlo y/o
# modificarlo bajo los términos de la Licencia Pública General de GNU
# según la publicó la Fundación del Software Libre; ya sea la versión 3, o
# (a su elección) una versión superior.
#
# Este programa se distribuye con la esperanza de que sea útil,
# pero SIN NINGUNA GARANTIA; ni siquiera la garantía implícita de
# COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO DETERMINADO. Vea la
# Licencia Pública General de GNU para más detalles.
#
# Deberías haber recibido una copia de la Licencia Pública General
# de GNU junto con este software; mira el fichero LICENSE. Si
# no, mira <https://www.gnu.org/licenses/>.

# Author: Ulpiano Tur de Vargas <ulpiano.tur.devargas@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this software; see the file LICENSE. If
# not, see <https://www.gnu.org/licenses/>.

@include "funcs_ssdv.awk";
@include "funcs_http.awk";

@load "fork"
@load "sereno"

BEGIN {
    Opterr = 0;
    Optind = 1;
    ProcesaOpciones_ssdv(ARGC, ARGV);

    delete lcfg;
    LeeConfiguracion_ssdv(Opcn["ruta_conf"], lcfg);

    i = 0;
    while ((dom = trae(lcfg, "dominio.[" ++i "].nombre")) != "") {
        rut = trae(lcfg, "dominio.[" i "].ruta_contenido");
        Indexar_contenido_ssdv(dom, rut);
        LSTDR[dom] = rut;
    }

    Inicia_http();

    canalTcpIP = "/inet/tcp/" trae(lcfg, "general.puerto") "/0/0";    

    max = trae(lcfg, "general.numero_maximo_hilos");
    for (i = 0; i < max; i++)
        p[i] = Crea_proceso(canalTcpIP);

    wait();
}

function Crea_proceso(canalTcpIP,      pid)
{
    if ((pid = fork()) == 0)
        Un_proceso(canalTcpIP);

    return pid;
}

function Un_proceso(canalTcpIP,      EntSal)
{
    for (;;) {
        # Sondea E/S. Espera hasta poder leer y escribir en canal TCP/IP
	    delete EntSal;
        trae_es(canalTcpIP, "|&", EntSal);
        sondea(EntSal);
	    #vigila(EntSal);

        # Genera LineaIniPetHttp, CabeceraPetHttp
        LeePeticion_http(canalTcpIP);

        # Borra cabeceras respuesta anterior
        delete CabeceraResHttp;
        # Genera LineaEstResHttp
        ProcesaPeticion_http(LineaIniPetHttp, CabeceraPetHttp);

        # Genera CabeceraResHttp
        EnviaRespuesta_http(LineaEstResHttp, canalTcpIP);

        close(canalTcpIP);
    }
}
